default_platform(:ios)

platform :ios do
  desc "Push iOS localized text (metadata) to App Store Connect"
  lane :upload_metadata do
    # Force Fastlane to authenticate via the API Key instead of Apple ID Password
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_API_KEY_KEY_FILEPATH"],
      in_house: false
    )

    deliver(
      api_key: api_key,
      skip_screenshots: true,
      skip_metadata: false,          # ENSURE THIS IS FALSE TO PUSH ALL METADATA
      overwrite_screenshots: false,
      submit_for_review: false,
      force: true,
      skip_binary_upload: true,
      ignore_language_directory_validation: true, # Safety catch for unsupported folders
      run_precheck_before_submit: false,         # Fixes API Key compatibility error
    )
  end

  desc "Deploy a new version to the App Store (IPA + Release Notes)"
  lane :release do
    api_key = app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_API_KEY_ISSUER_ID"],
      key_filepath: ENV["APP_STORE_CONNECT_API_KEY_KEY_FILEPATH"],
      in_house: false
    )

    deliver(
      api_key: api_key,
      ipa: "build/ios/ipa/split_bill_app.ipa",
      skip_screenshots: true,
      skip_metadata: false,          # ENSURE THIS IS FALSE TO PUSH ALL METADATA
      force: true,
      submit_for_review: false,
      run_precheck_before_submit: false,         # Fixes API Key compatibility error
    )
  end
end

platform :android do
  desc "Push Android localized text (metadata) to Google Play Console"
  lane :upload_metadata do
    supply(
      skip_upload_apk: true,          # Don't upload an app bundle right now
      skip_upload_aab: true,
      skip_upload_images: true,       # Don't overwrite graphic assets
      skip_upload_screenshots: true,  # Don't overwrite existing localized screenshots
      skip_upload_changelogs: true,   # Prevent supply from requiring a version_code block
      metadata_path: "fastlane/metadata/android" # Point to the Android translation folder
    )
  end
  lane :deploy do
    desc "Deploy a new version to the Google Play Store (Production Track) with translated Release Notes"
    supply(
      track: "production",
      aab: "build/app/outputs/bundle/release/app-release.aab",
      metadata_path: "fastlane/metadata/android",
      skip_upload_metadata: false,     # ENSURE THIS IS FALSE TO PUSH NEW DESCRIPTIONS
      skip_upload_images: true,        # Don't push graphic assets
      skip_upload_screenshots: true,   # Don't push screenshots
      skip_upload_changelogs: false,   # Push changelogs
    )
  end
end
